version: 2

sources:
    - name: stg
      schema: public
      tables:
          - name: customer
            indentifier: dim_customer
          - name: address
          - name: city
          - name: country
          - name: film
          - name: film_actor
          - name: film_category
          - name: inventory
          - name: language
          - name: payment
          - name: rental
          - name: staff
          - name: store
          - name: actor
          - name: category
